### ISSUE TITLE
Redirection of input to ish

### ISSUE THREAD

**Issue by daniiarov-alym** [toksaitov/syscall-project#3]
I am not sure whether it is actually a bug, but if I create a file `temp` with contents 
```
echo foo
```
and redirect it to `bash` I will get 
```
$ bash < temp
e
```
as expected. 

While for `ish` the output is:
```
./ish < temp
foo


// A lot more blank lines here
```
Seems like ish has some problem with input redirection here.

UPD. Situation is reproducible inside ish itself.

UPD 2. The same is observed with piping (`echo "echo foo" | ./ish`)

**Comment by daniiarov-alym** [comment]
Actually, there is also a problem that even after changes that are suggested in #4 are done there is still problem. First of all:

If i do 
`$ echo -n 'echo foo' | ./ish`
instead of expected output 
`foo` 
I get 
`foo�G�`

The fix is probably that there should be not just loop `while (read() > 0)`  but the amount of bytes read should be stored in somewhere and used.

**Comment by toksaitov** [comment]
I have accepted the PR and made minor [changes](https://github.com/toksaitov/syscall-project/commit/0fea2df3e416626217fb1cf08caed1209595ea09) to consider the `bytes read` info from the `read` system call.
